### ISSUE TITLE
Move calculation of kinderzuschlag_max

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#321] opened 2022-01-05 12:46 UTC
# Current situation

In PR #267, we solved the new calculation for the maximum kinderzuschlag by setting the `kinderzuschlag_max` in `policy_enviroment.py` ([link](https://github.com/iza-institute-of-labor-economics/gettsim/blob/ac0ae8cc28ba76adf7a0931f79b093e193d85e41/gettsim/policy_environment.py#L145-L174)).  While this works fine, this is not the place one would look for it. 

# Suggestion
by @mjbloemer :

> Why not simply add a new year switch (two functions) there where ..bis_2020 is equal to the parameter and ..since_2021 is a function of the ExMin and KG parameters? Just another level of function composition instead of overwriting parameters?

**Comment by hmgaudecker** [comment] 2022-01-07 12:25
The problem is that if it was placed in `kinderzuschlag.py`, it would become part of the DAG. That's why we put it where it is.

But I think this should actually happen! It is also a good example of the value of setting `kinderzuschlag_max` to `null` starting in 2021.

The function could just be (untested)

```python
def kinderzuschlag_max(hh_id, kinderzuschlag_params, kindergeld_params):
    if kinderzuschlag_params["kinderzuschlag_max"] is not None:
        out_scalar = kinderzuschlag_params["kinderzuschlag_max"]
    else:
        params["kinderzuschlag"]["kinderzuschlag_max"] = (
            params["kinderzuschlag"]["exmin"]["regelsatz"]["kinder"]
            + params["kinderzuschlag"]["exmin"]["kosten_der_unterkunft"]["kinder"]
            + params["kinderzuschlag"]["exmin"]["heizkosten"]["kinder"]
        ) / 12 - params["kindergeld"]["kindergeld"][1]

    return pd.Series(out_scalar, index=hh_id)
```

(stuff under `else` just taken from current function)

**Comment by ChristianZimpelmann** [comment] 2022-01-07 13:07
Shouldn't it rather be `if "kinderzuschlag_max" not in
kinderzuschlag_params`?


Am Fr., 7. Jan. 2022 um 13:25 Uhr schrieb Hans-Martin von Gaudecker <
***@***.***>:

**Comment by ChristianZimpelmann** [comment] 2022-01-07 13:09
Shouldn't it rather be:

`if "kinderzuschlag_max" not in kinderzuschlag_params: `

**Comment by Eric-Sommer** [comment] 2022-01-07 13:12
> Shouldn't it rather be:
> 
> `if "kinderzuschlag_max" not in kinderzuschlag_params: `

I agree. @mjbloemer is however right in pointing out that this leads to errors before 2004 when there is no [`exmin`] parameter. So maybe
`if "kinderzuschlag_max" not in kinderzuschlag_params:  and "exmin" in kinderzuschlag_params`

**Comment by mjbloemer** [comment] 2022-01-07 13:14
My point was not about the exmin parameter, but that there is no Kinderzuschlag prior to 2005.

**Comment by hmgaudecker** [comment] 2022-01-07 13:48
> Shouldn't it rather be:
> 
> `if "kinderzuschlag_max" not in kinderzuschlag_params: `

Thanks! Almost. I fixed it above directly

**Comment by hmgaudecker** [comment] 2022-01-07 14:04
> My point was not about the exmin parameter, but that there is no Kinderzuschlag prior to 2005.

And you are completely right, of course. You're just too fast for me :wink: 

I added that to GEP-04, we'll need to find a good way of handling such cases at the function level. The *function* `kinderzuschlag_max` should not be part of the DAG prior to the existence of `kinderzuschlag`. 

See [here](https://github.com/iza-institute-of-labor-economics/gettsim/pull/178/files#diff-247bc3d18beb5b6a7278964e79ca801acf1ef13f5f0a01b416e13f88c5cd7508), docs take a while to build, we probably committed too much today.

**Comment by MImmesberger** [comment] 2024-08-28 14:49
Only part missing is #789. Hence, I'll close this one as completed.

**Closed by MImmesberger** 2024-08-28 14:49 UTC
Labels: structure-design
